services:
  nextjs-service:
    build:
      context: ./../../
      dockerfile: ./docker/development/Dockerfile.nextjs
    container_name: test-beglarian-nextjs
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - ./../../.env
    environment:
      VIPS_CONCURRENCY: 16 # Value of thread mathcing number of CPU cores
    volumes:
      - ./../..:/app
      - /app/node_modules
